ansible_host: "{{ lookup('env', 'RPI_HOST') | default('raspberrypi.local', true) }}"
ansible_user: "{{ lookup('env', 'RPI_USER') | default('pi', true) }}"

docker_user: "{{ lookup('env', 'RPI_USER') | default('pi', true) }}"

ansible_python_interpreter: /usr/bin/python3

photos_lv_path: "{{ lookup('env', 'PHOTOS_LV_PATH') | default('', true) }}"
photos_mount_path: "{{ lookup('env', 'PHOTOS_PATH') | default('/mnt/photos', true) }}"
