---
- name: Configure Raspberry Pi
  hosts: rpi
  become: true

  roles:
    - role: system
      tags: system
    - role: docker
      tags: docker
    - role: tailscale
      tags: tailscale
    - role: immich
      tags: immich
    - role: immich_public_proxy
      tags: immich_public_proxy
    - role: cloudflared
      tags: cloudflared
