---
- name: Add Tailscale GPG key
  ansible.builtin.shell:
    cmd: >
      curl -fsSL https://pkgs.tailscale.com/stable/debian/{{ ansible_facts['lsb']['codename'] }}.noarmor.gpg |
      tee /usr/share/keyrings/tailscale-archive-keyring.gpg > /dev/null
    creates: /usr/share/keyrings/tailscale-archive-keyring.gpg

- name: Add Tailscale apt repository
  ansible.builtin.get_url:
    url: "https://pkgs.tailscale.com/stable/debian/{{ ansible_facts['lsb']['codename'] }}.tailscale-keyring.list"
    dest: /etc/apt/sources.list.d/tailscale.list
    mode: "0644"

- name: Install Tailscale
  ansible.builtin.apt:
    name: tailscale
    state: present
    update_cache: true

- name: Enable and start tailscaled
  ansible.builtin.systemd:
    name: tailscaled
    enabled: true
    state: started

- name: Check Tailscale status
  ansible.builtin.command: tailscale status
  register: tailscale_status
  changed_when: false
  failed_when: false

- name: Bring up Tailscale
  ansible.builtin.command: >
    tailscale up
    --auth-key={{ tailscale_auth_key }}
    --accept-dns
    --ssh
  when:
    - tailscale_auth_key != ''
    - "'Logged out' in tailscale_status.stdout or tailscale_status.rc != 0"
